// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiA2Nc11qZs8pmWeCkWxGsmYo6zUy4TMU',
    appId: '1:681392533528:web:f22792582669ff0634536d',
    messagingSenderId: '681392533528',
    projectId: 'gybbase',
    authDomain: 'gybbase.firebaseapp.com',
    storageBucket: 'gybbase.firebasestorage.app',
    measurementId: 'G-8HW4QYRZC3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBetR4-FcW-StaSM0VIRdFxg0bH4FNTtMU',
    appId: '1:681392533528:android:1b43e0b5873ac2cd34536d',
    messagingSenderId: '681392533528',
    projectId: 'gybbase',
    storageBucket: 'gybbase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkS_7esK2qIGVFCM5xUXOOTE8xliYw4eA',
    appId: '1:681392533528:ios:9ca5423ff77ae1a834536d',
    messagingSenderId: '681392533528',
    projectId: 'gybbase',
    storageBucket: 'gybbase.firebasestorage.app',
    iosBundleId: 'com.example.gymTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkS_7esK2qIGVFCM5xUXOOTE8xliYw4eA',
    appId: '1:681392533528:ios:9ca5423ff77ae1a834536d',
    messagingSenderId: '681392533528',
    projectId: 'gybbase',
    storageBucket: 'gybbase.firebasestorage.app',
    iosBundleId: 'com.example.gymTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiA2Nc11qZs8pmWeCkWxGsmYo6zUy4TMU',
    appId: '1:681392533528:web:3b27b202717d13c934536d',
    messagingSenderId: '681392533528',
    projectId: 'gybbase',
    authDomain: 'gybbase.firebaseapp.com',
    storageBucket: 'gybbase.firebasestorage.app',
    measurementId: 'G-WL6VB0E5P0',
  );
}
